version: '3.1'

services:

  db:
      image: postgres
      restart: always
      # set shared memory limit when using docker-compose
      shm_size: 128mb
      # or set shared memory limit when deploy via swarm stack
      #volumes:
      #  - type: tmpfs
      #    target: /dev/shm
      #    tmpfs:
      #      size: 134217728 # 128*2^20 bytes = 128Mb
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_DB: drizz

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    
  backend:
    build: backend/
    container_name: backend_drizz
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - adminer
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
      MYSQL_HOST: db
      MYSQL_DATABASE: homestead